### ISSUE TITLE
FrozenClipEmbedder vs FrozenOpenClipEmbedder

### ISSUE THREAD

**Issue by shileims** [lucidrains/perfusion-pytorch#10]
Hi Author,
    I think the original SD1.5 was using FrozenClipEmbedder, but yours is FrozenOpenClipEmbedder, how should I cope with their difference? Thanks

**Comment by lucidrains** [comment]
@shileims i made the wrapper a bit more flexible

the internal modules should be identical save for a few minor differences

**Comment by shileims** [comment]
Thank you!
