### ISSUE TITLE
How about superclass_string has two token ids?

### ISSUE THREAD

**Issue by shileims** [lucidrains/perfusion-pytorch#11]
Hi Author,
    If the superclass_string has two token ids, should we still get the only first token id?

    ids = tokenize([superclass_string])**[0]**
     assert ids.shape[-1] == 1, f'your superclass concept string must map exactly one token id'
     superclass_embed_id = ids**[0].**item()

Like the index with bold text, should we still get only the first token id? Thanks

**Comment by lucidrains** [comment]
yeah, so that may be the drawback to this technique for now

you need superclass concepts that are only one token

**Comment by lucidrains** [comment]
maybe for the follow up paper, if this technique holds up

**Comment by shileims** [comment]
Thank you！
