### ISSUE TITLE
How to define the target input: i*?

### ISSUE THREAD

**Issue by shileims** [lucidrains/perfusion-pytorch#12]
Hi Author,
    While defining the target input i*, should I define it like this:         
self.register_buffer('target_input', torch.empty(self.model.diffusion_model.context_dim, dtype=torch.float32))
?

Thanks

**Comment by lucidrains** [comment]
you don't need to define it; that is all taken care of for you in the Rank1EditModule automagically

**Comment by lucidrains** [comment]
https://github.com/lucidrains/perfusion-pytorch/blob/main/perfusion_pytorch/perfusion.py#L151

**Comment by shileims** [comment]
Hi @lucidrains ,
     Thanks for your reply.
     Should I replace the linear projection of v in the cross_attention with Rank1ModelEditing?

**Comment by shileims** [comment]
Hi @lucidrains ,
     Just a kindly ask. Would you have a pseudo code or flowchart for the whole training picture?
     If yes, that will be helpful. Thanks
