### ISSUE TITLE
Trainable "ema_concept_text_encs" for both key and value, but concept_outputs is only trainable for value. Is it correct?

### ISSUE THREAD

**Issue by shileims** [lucidrains/perfusion-pytorch#13]
Hi Author,
    Trainable "ema_concept_text_encs" for both key and value, but concept_outputs is only trainable for value. Is my understanding correct? Thanks

**Comment by lucidrains** [comment]
yes that is correct, to the best of my understanding

**Comment by shileims** [comment]
Thank you!
