### ISSUE TITLE
BearType error when using get_finetune_optimizer()

### ISSUE THREAD

**Issue by irowberry** [lucidrains/perfusion-pytorch#14]
The error is `type <class '__main__.PerfusionModel'> not instance of <class "torch.nn.modules.module.Module">`. 
However I am using this to define the Perfusion model. 
`
class PerfusionModel(nn.Module):
    def __init__(self, unet, clip_model, superclass_string):
        super(PerfusionModel, self).__init__()
`

**Comment by lucidrains** [comment]
@irowberry can you show me the full code?

**Comment by irowberry** [comment]
I can, I'm just declaring the model class in main, which is why it gives that type `<class '__main__.PerfusionModel'>`. (https://stackoverflow.com/questions/48845989/understanding-class-type-main-classname)
The model is defined on line 119
[perfusion_test copy.txt](https://github.com/lucidrains/perfusion-pytorch/files/12526268/perfusion_test.copy.txt)

**Comment by lucidrains** [comment]
@irowberry you need to pass in the `perfusion_model` from two lines above that function

**Comment by irowberry** [comment]
Oh yeah duh, the instance not just the class, my bad.

**Comment by lucidrains** [comment]
@irowberry no problem, you are almost there 😄
