### ISSUE TITLE
NVIDIA implementation not available?

### ISSUE THREAD

**Issue by ShashwatNigam99** [lucidrains/perfusion-pytorch#2]
Just confirming if NVIDIA plans to release an implementation? Thanks for implementing this! Will you use the diffusers library?

**Comment by lucidrains** [comment]
i was told they are no longer open sourcing, which is why i'll just do it. no, i'll probably use the stable diffusion library from Rombach et al.

**Comment by lucidrains** [comment]
i should probably also knock out that Brain hypernetworks paper, while i'm looking at this topic

**Comment by lucidrains** [comment]
@ShashwatNigam99 if they do change their minds and open source the code, let me know

**Comment by lucidrains** [comment]
ahh, good news, the first author has reached out and graciously agreed to do a code review once i get to a new landmark

**Comment by lucidrains** [comment]
does anyone have the link to that hypernetworks paper? I lost it 😑

**Comment by ViddleShtix** [comment]
Hyper Dreambooth? https://hyperdreambooth.github.io/
Implementation:
https://github.com/KohakuBlueleaf/HyperKohaku

**Comment by lucidrains** [comment]
@BradVidler that's the one! and Kohaku already took care of it! 🙌

**Comment by GitHub1712** [comment]
That´s a shame for Nvidia, getting attraction with a "code coming soon - open source project" and just removing the flag if there was enough attraction. Thank you for the work!
