### ISSUE TITLE
Hey there, is there a tutorial on how to use this for image training?

### ISSUE THREAD

**Issue by Iommed** [lucidrains/perfusion-pytorch#3]
I'd be thrilled, thanks. Assume I know nothing, very new to this stuff. I've looked at the Usage info but still have questions; do I run the Usage on Perfusion.py or in a separate command? etc. I'll kind of have to start from scratch on learning this.

**Comment by lucidrains** [comment]
I'm still waiting for one last review from the author before wiring it up with SD. also want to get done the logic for composing multiple concepts at inference. Eta prob 1 week

Feel free to poke around, for educational purposes or if you feel ambitious and want to give it a go wiring it all up. most of the main contribution of the paper is there

**Comment by Iommed** [comment]
Appreciate the reply! I'll wait for updates then.

**Comment by Kyfafyd** [comment]
Thanks for your implementation! Any updates for this?
