### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by inspirit** [lucidrains/perfusion-pytorch#4]
Hi Phil! great work as usual! :)
I recently came across kind of a similar work from Tencent (https://ip-adapter.github.io/)
Might be interesting to combine ideas from perfusion and ip-adapter works :)

**Comment by lucidrains** [comment]
Thanks Eugene

I'm not planning on investing more time in this field of research after this project, but you are welcome to fork and combine the concepts. That paper does not look complicated to implement

**Comment by ViddleShtix** [comment]
It is already implemented. They released the code with the paper. It’s very simple to use with diffusers but quite a different use case than Perfusion.

p.s. just want to say thanks for your work on Perfusion. Can’t wait to test it.

**Comment by lucidrains** [comment]
@BradVidler no problem, still waiting for a final review from Yoad

if Yoad had not offered to correspond, I think this would have taken 2-3x longer. I misunderstood a few things in the paper
